import {themes as prismThemes} from 'prism-react-renderer';
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

// Centralized version - update version.json when releasing
const versionConfig = require('./version.json');
const VERSION = versionConfig.version;

const config: Config = {
  title: 'UnDercontrol',
  tagline: 'One workspace for tasks, knowledge, and AI agents — private, portable, yours.',
  favicon: 'img/favicon.svg',

  future: {
    v4: true,
  },

  url: 'https://oatnil.com',
  baseUrl: '/',

  organizationName: 'oatnil-top',
  projectName: 'ud-docs',

  onBrokenLinks: 'throw',
  onBrokenMarkdownLinks: 'warn',

  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'zh-Hans'],
    localeConfigs: {
      en: {
        label: 'English',
        direction: 'ltr',
        htmlLang: 'en-US',
      },
      'zh-Hans': {
        label: '简体中文',
        direction: 'ltr',
        htmlLang: 'zh-Hans',
      },
    },
  },

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          editUrl:
            'https://github.com/oatnil-top/ud-docs/tree/main/',
        },
        blog: {
          showReadingTime: true,
          feedOptions: {
            type: ['rss', 'atom'],
            xslt: true,
          },
          editUrl:
            'https://github.com/oatnil-top/ud-docs/tree/main/',
          onInlineTags: 'warn',
          onInlineAuthors: 'warn',
          onUntruncatedBlogPosts: 'warn',
        },
        theme: {
          customCss: './src/css/custom.css',
        },
        gtag: {
          trackingID: 'G-B3E5P48S9Y',
          anonymizeIP: true,
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    /*
     * Dark mode was never something this site opted into — with no colorMode
     * block at all it ran on Docusaurus' defaults, which means the toggle has
     * been in the navbar and a dark palette has been shipping all along, only
     * half-styled. So we ADD to that machinery rather than take it over: the
     * switch stays `[data-theme='dark']`, our colours are Infima variables,
     * and nothing here swizzles ColorModeProvider (whose SSR anti-flash
     * script is exactly the part you do not want to re-implement).
     *
     * respectPrefersColorScheme was false, so a visitor whose OS is in dark
     * mode still landed on the light site. Turning it true is deliberately
     * the LAST change of this batch (ud task 8496fc04): from this line
     * onwards the dark palette is what those visitors see first, so it had to
     * be finished before the switch was thrown, not after.
     */
    colorMode: {
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: 'UnDercontrol',
      logo: {
        alt: 'UnDercontrol Logo',
        src: 'img/favicon.svg',
      },
      // Three destinations on the left, three controls on the right — the
      // header's shape copied from the reference page (ud task d9f0567c):
      // plain text (there, a login; here, the locale switch) → outlined button
      // → filled button. Self-Host moved from the left group into the outlined
      // slot; it was not invented for the slot, it is our own main path.
      // No dropdown chevrons on the left three: none of them has a submenu,
      // and a chevron would draw a feature that does not exist.
      // Cookbook lives in the Docs sidebar (autogenerated); version, Privacy,
      // Contact and GitHub live in the footer, the only other site-wide surface.
      items: [
        {
          type: 'docSidebar',
          sidebarId: 'docsSidebar',
          position: 'left',
          label: 'Docs',
        },
        {to: '/alfred', label: 'Alfred', position: 'left'},
        {to: '/blog', label: 'Blog', position: 'left'},
        {
          type: 'localeDropdown',
          position: 'right',
        },
        {
          to: '/self-hosting',
          label: 'Self-Host',
          position: 'right',
          className: 'navbar__outline',
        },
        {
          to: '/download',
          label: 'Download',
          position: 'right',
          className: 'navbar__cta',
        },
      ],
    },
    // The footer is the landing surface for everything the navbar sheds, so it
    // must stay visible — see the .footer rules in src/css/custom.css.
    footer: {
      style: 'light',
      links: [
        {
          title: 'Product',
          items: [
            {
              label: 'Download',
              to: '/download',
            },
            {
              label: 'Pricing',
              to: '/subscribe',
            },
            {
              label: 'Self-Host',
              to: '/self-hosting',
            },
            {
              label: 'Cookbook',
              to: '/docs/cookbook',
            },
          ],
        },
        {
          title: 'Docs',
          items: [
            {
              label: 'Getting Started',
              to: '/docs/intro',
            },
            {
              label: 'Blog',
              to: '/blog',
            },
            {
              label: 'Chrome Extension',
              href: 'https://github.com/oatnil-top/ud-chrome-extension',
            },
          ],
        },
        {
          title: 'Community',
          items: [
            // The components page, not a repo link: it is the surface that
            // says which repositories are published and under what license.
            // The "Chrome Extension" entry above points at the same repo URL
            // the page's card does, so the two never send a reader elsewhere.
            {
              label: 'Open Source Components',
              to: '/open-source',
            },
            {
              label: 'Discord',
              href: 'https://discord.gg/vkw2nhxE',
            },
            {
              label: 'GitHub',
              href: 'https://github.com/oatnil-top/ud-docs',
            },
            {
              label: 'GitHub Discussions',
              href: 'https://github.com/oatnil-top/ud-docs/discussions',
            },
          ],
        },
        {
          title: 'More',
          items: [
            {
              label: 'Contact',
              to: '/contact',
            },
            {
              label: 'Privacy Policy',
              to: '/privacy',
            },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} UnDercontrol Project · v${VERSION}`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
