import {themes as prismThemes} from 'prism-react-renderer';
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

// Centralized version - update version.json when releasing
const versionConfig = require('./version.json');
const VERSION = versionConfig.version;

const config: Config = {
  title: 'UnDercontrol',
  tagline: 'One workspace for tasks, knowledge, and AI agents — private, portable, yours.',
  favicon: 'img/favicon.svg',

  future: {
    v4: true,
  },

  url: 'https://oatnil.com',
  baseUrl: '/',

  organizationName: 'oatnil-top',
  projectName: 'ud-docs',

  onBrokenLinks: 'throw',
  onBrokenMarkdownLinks: 'warn',

  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'zh-Hans'],
    localeConfigs: {
      en: {
        label: 'English',
        direction: 'ltr',
        htmlLang: 'en-US',
      },
      'zh-Hans': {
        label: '简体中文',
        direction: 'ltr',
        htmlLang: 'zh-Hans',
      },
    },
  },

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          editUrl:
            'https://github.com/oatnil-top/ud-docs/tree/main/',
        },
        blog: {
          showReadingTime: true,
          feedOptions: {
            type: ['rss', 'atom'],
            xslt: true,
          },
          editUrl:
            'https://github.com/oatnil-top/ud-docs/tree/main/',
          onInlineTags: 'warn',
          onInlineAuthors: 'warn',
          onUntruncatedBlogPosts: 'warn',
        },
        theme: {
          customCss: './src/css/custom.css',
        },
        gtag: {
          trackingID: 'G-B3E5P48S9Y',
          anonymizeIP: true,
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    navbar: {
      title: 'UnDercontrol',
      logo: {
        alt: 'UnDercontrol Logo',
        src: 'img/favicon.svg',
      },
      // Kept to three destinations plus one CTA. Cookbook lives in the Docs
      // sidebar (autogenerated); version, Privacy, Contact and GitHub moved to
      // the footer, which is the only other site-wide surface.
      items: [
        {
          type: 'docSidebar',
          sidebarId: 'docsSidebar',
          position: 'left',
          label: 'Docs',
        },
        {to: '/blog', label: 'Blog', position: 'left'},
        {
          to: '/self-hosting',
          label: 'Self-Host',
          position: 'left',
        },
        {
          type: 'localeDropdown',
          position: 'right',
        },
        {
          to: '/subscribe',
          label: 'Download',
          position: 'right',
          className: 'navbar__cta',
        },
      ],
    },
    // The footer is the landing surface for everything the navbar sheds, so it
    // must stay visible — see the .footer rules in src/css/custom.css.
    footer: {
      style: 'light',
      links: [
        {
          title: 'Product',
          items: [
            {
              label: 'Download',
              to: '/subscribe',
            },
            {
              label: 'Self-Host',
              to: '/self-hosting',
            },
            {
              label: 'Cookbook',
              to: '/docs/cookbook',
            },
          ],
        },
        {
          title: 'Docs',
          items: [
            {
              label: 'Getting Started',
              to: '/docs/intro',
            },
            {
              label: 'Blog',
              to: '/blog',
            },
            {
              label: 'Chrome Extension',
              href: 'https://github.com/oatnil-top/ud-chrome-extension',
            },
          ],
        },
        {
          title: 'Community',
          items: [
            {
              label: 'Discord',
              href: 'https://discord.gg/vkw2nhxE',
            },
            {
              label: 'GitHub',
              href: 'https://github.com/oatnil-top/ud-docs',
            },
            {
              label: 'GitHub Discussions',
              href: 'https://github.com/oatnil-top/ud-docs/discussions',
            },
          ],
        },
        {
          title: 'More',
          items: [
            {
              label: 'Contact',
              to: '/contact',
            },
            {
              label: 'Privacy Policy',
              to: '/docs/privacy',
            },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} UnDercontrol Project · v${VERSION}`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
